from PyQt5 import QtCore, QtGui, QtWidgets


class UiAboutPage(object):
    def setup_ui(self, about_page):
        about_page.setObjectName("about_page")
        about_page.resize(350, 221)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        about_page.setFont(font)
        about_page.setStyleSheet("QWidget{background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #3e92ff, stop:.6 #3e92ff, stop:1 #3ebfff);} QLabel{background: transparent}")
        self.gridLayoutWidget = QtWidgets.QWidget(about_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 331, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.author = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.author.setFont(font)
        self.author.setStyleSheet("")
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 0, 1, 1, 1)
        self.email = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setStyleSheet("")
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.widget = QtWidgets.QWidget(about_page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 351, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setStyleSheet("QWidget{background: #d5e2e8;}")
        self.widget.setObjectName("widget")
        self.icon = QtWidgets.QLabel(self.widget)
        self.icon.setGeometry(QtCore.QRect(10, 10, 64, 64))
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(90, 16, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setObjectName("name")
        self.version = QtWidgets.QLabel(self.widget)
        self.version.setGeometry(QtCore.QRect(95, 45, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.widget_2 = QtWidgets.QWidget(about_page)
        self.widget_2.setGeometry(QtCore.QRect(0, 170, 351, 51))
        self.widget_2.setStyleSheet("QWidget{background: #e6e6e6;}")
        self.widget_2.setObjectName("widget_2")
        self.thanks_label = QtWidgets.QLabel(self.widget_2)
        self.thanks_label.setGeometry(QtCore.QRect(0, 0, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.thanks_label.setFont(font)
        self.thanks_label.setStyleSheet("")
        self.thanks_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thanks_label.setObjectName("thanks_label")
        self.ok_bt = QtWidgets.QPushButton(self.widget_2)
        self.ok_bt.setGeometry(QtCore.QRect(273, 13, 71, 25))
        self.ok_bt.setObjectName("ok_bt")

        self.label_5.setText("Email :")
        self.label_3.setText("Author :")
        self.author.setText("Md. Nayeeem")
        self.email.setText("nayemmia898@gmail.com")
        self.name.setText("Calculator")
        self.version.setText("v1.2.2")
        self.thanks_label.setText("Thanks for using this software")
        self.ok_bt.setText("Ok")

        self.ok_bt.clicked.connect(about_page.close)
        QtCore.QMetaObject.connectSlotsByName(about_page)
