from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutPage(object):
    def setupUi(self, AboutPage):
        AboutPage.setWindowModality(QtCore.Qt.ApplicationModal)
        AboutPage.resize(350, 215)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        AboutPage.setFont(font)
        AboutPage.setWindowTitle("About")
        AboutPage.setStyleSheet("QWidget{background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #3e92ff, stop:.6 #3e92ff, stop:1 #3ebfff);} QLabel{background: transparent}")
        self.gridLayoutWidget = QtWidgets.QWidget(AboutPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 331, 71))
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setText("Email :")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("Author :")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.author = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.author.setFont(font)
        self.author.setText("Md. Nayeem")
        self.gridLayout.addWidget(self.author, 0, 1, 1, 1)
        self.email = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setText("nayeem.code@gmail.com")
        self.gridLayout.addWidget(self.email, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.widget = QtWidgets.QWidget(AboutPage)
        self.widget.setGeometry(QtCore.QRect(0, 0, 351, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setStyleSheet("QWidget{background: #d5e2e8;}")
        self.icon = QtWidgets.QLabel(self.widget)
        self.icon.setGeometry(QtCore.QRect(10, 10, 64, 64))
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(90, 16, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.version = QtWidgets.QLabel(self.widget)
        self.version.setGeometry(QtCore.QRect(95, 45, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.widget_2 = QtWidgets.QWidget(AboutPage)
        self.widget_2.setGeometry(QtCore.QRect(0, 170, 351, 51))
        self.widget_2.setStyleSheet("QWidget{background: #e6e6e6;}")
        self.thanks_label = QtWidgets.QLabel(self.widget_2)
        self.thanks_label.setGeometry(QtCore.QRect(0, 0, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.thanks_label.setFont(font)
        self.thanks_label.setText("Thanks for using this software")
        self.thanks_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ok_bt = QtWidgets.QPushButton(self.widget_2)
        self.ok_bt.setGeometry(QtCore.QRect(273, 13, 71, 25))
        self.ok_bt.setText("Ok")
        self.ok_bt.clicked.connect(AboutPage.close)
        
class Ui_ShortcutPage(object):
    def setupUi(self, ShortcutPage):
        ShortcutPage.setObjectName("ShortcutPage")
        ShortcutPage.setWindowModality(QtCore.Qt.ApplicationModal)
        ShortcutPage.resize(360, 450)
        font = QtGui.QFont()
        font.setPointSize(10)
        ShortcutPage.setFont(font)
        self.gridLayout_4 = QtWidgets.QGridLayout(ShortcutPage)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(ShortcutPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background: #d1d1d1;")
        self.label.setText("Shortcuts")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(ShortcutPage)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.l3_2 = QtWidgets.QLabel(self.tab_1)
        self.l3_2.setText("Cut")
        self.l3_2.setObjectName("l3_2")
        self.gridLayout.addWidget(self.l3_2, 2, 0, 1, 1)
        self.l4_2 = QtWidgets.QLabel(self.tab_1)
        self.l4_2.setText("Ctrl + X")
        self.l4_2.setObjectName("l4_2")
        self.gridLayout.addWidget(self.l4_2, 2, 1, 1, 1)
        self.l11_9 = QtWidgets.QLabel(self.tab_1)
        self.l11_9.setText("Previous History")
        self.l11_9.setObjectName("l11_9")
        self.gridLayout.addWidget(self.l11_9, 8, 0, 1, 1)
        self.l11_10 = QtWidgets.QLabel(self.tab_1)
        self.l11_10.setText("Ctrl + Z")
        self.l11_10.setObjectName("l11_10")
        self.gridLayout.addWidget(self.l11_10, 8, 1, 1, 1)
        self.l11_11 = QtWidgets.QLabel(self.tab_1)
        self.l11_11.setText("Exit")
        self.l11_11.setObjectName("l11_11")
        self.gridLayout.addWidget(self.l11_11, 10, 0, 1, 1)
        self.l11_12 = QtWidgets.QLabel(self.tab_1)
        self.l11_12.setText("Ctrl + Q")
        self.l11_12.setObjectName("l11_12")
        self.gridLayout.addWidget(self.l11_12, 10, 1, 1, 1)
        self.l11_3 = QtWidgets.QLabel(self.tab_1)
        self.l11_3.setText("Next History")
        self.l11_3.setObjectName("l11_3")
        self.gridLayout.addWidget(self.l11_3, 9, 0, 1, 1)
        self.l1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setText("Action")
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 0, 0, 1, 1)
        self.l2 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setText("Shortcut")
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 0, 1, 1, 1)
        self.l8 = QtWidgets.QLabel(self.tab_1)
        self.l8.setText("Ctrl + F")
        self.l8.setObjectName("l8")
        self.gridLayout.addWidget(self.l8, 5, 1, 1, 1)
        self.l7 = QtWidgets.QLabel(self.tab_1)
        self.l7.setText("Fullscreen mode")
        self.l7.setObjectName("l7")
        self.gridLayout.addWidget(self.l7, 5, 0, 1, 1)
        self.l4 = QtWidgets.QLabel(self.tab_1)
        self.l4.setText("Ctrl + C")
        self.l4.setObjectName("l4")
        self.gridLayout.addWidget(self.l4, 1, 1, 1, 1)
        self.l5 = QtWidgets.QLabel(self.tab_1)
        self.l5.setText("Paste")
        self.l5.setObjectName("l5")
        self.gridLayout.addWidget(self.l5, 3, 0, 1, 1)
        self.l6 = QtWidgets.QLabel(self.tab_1)
        self.l6.setText("Ctrl + V")
        self.l6.setObjectName("l6")
        self.gridLayout.addWidget(self.l6, 3, 1, 1, 1)
        self.l3 = QtWidgets.QLabel(self.tab_1)
        self.l3.setText("Copy")
        self.l3.setObjectName("l3")
        self.gridLayout.addWidget(self.l3, 1, 0, 1, 1)
        self.l9 = QtWidgets.QLabel(self.tab_1)
        self.l9.setText("Show Shortcuts")
        self.l9.setObjectName("l9")
        self.gridLayout.addWidget(self.l9, 6, 0, 1, 1)
        self.l10 = QtWidgets.QLabel(self.tab_1)
        self.l10.setText("Ctrl + S")
        self.l10.setObjectName("l10")
        self.gridLayout.addWidget(self.l10, 6, 1, 1, 1)
        self.l11_4 = QtWidgets.QLabel(self.tab_1)
        self.l11_4.setText("Ctrl + Shift + Z")
        self.l11_4.setObjectName("l11_4")
        self.gridLayout.addWidget(self.l11_4, 9, 1, 1, 1)
        self.l11_7 = QtWidgets.QLabel(self.tab_1)
        self.l11_7.setText("Clear History")
        self.l11_7.setObjectName("l11_7")
        self.gridLayout.addWidget(self.l11_7, 7, 0, 1, 1)
        self.l11_8 = QtWidgets.QLabel(self.tab_1)
        self.l11_8.setText("Ctrl + H")
        self.l11_8.setObjectName("l11_8")
        self.gridLayout.addWidget(self.l11_8, 7, 1, 1, 1)
        self.l7_2 = QtWidgets.QLabel(self.tab_1)
        self.l7_2.setText("Advance Screen")
        self.l7_2.setObjectName("l7_2")
        self.gridLayout.addWidget(self.l7_2, 4, 0, 1, 1)
        self.l8_2 = QtWidgets.QLabel(self.tab_1)
        self.l8_2.setText("F8")
        self.l8_2.setObjectName("l8_2")
        self.gridLayout.addWidget(self.l8_2, 4, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "General")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l17 = QtWidgets.QLabel(self.tab_2)
        self.l17.setText("Clear Memory (MC)")
        self.l17.setObjectName("l17")
        self.gridLayout_3.addWidget(self.l17, 4, 0, 1, 1)
        self.l20 = QtWidgets.QLabel(self.tab_2)
        self.l20.setText("Shift + M")
        self.l20.setObjectName("l20")
        self.gridLayout_3.addWidget(self.l20, 5, 1, 1, 1)
        self.l18 = QtWidgets.QLabel(self.tab_2)
        self.l18.setText("Ctrl + M")
        self.l18.setObjectName("l18")
        self.gridLayout_3.addWidget(self.l18, 4, 1, 1, 1)
        self.l19 = QtWidgets.QLabel(self.tab_2)
        self.l19.setText("Add to memory (M+)")
        self.l19.setObjectName("l19")
        self.gridLayout_3.addWidget(self.l19, 5, 0, 1, 1)
        self.l14 = QtWidgets.QLabel(self.tab_2)
        self.l14.setText("Alt + C")
        self.l14.setObjectName("l14")
        self.gridLayout_3.addWidget(self.l14, 1, 1, 1, 1)
        self.l15 = QtWidgets.QLabel(self.tab_2)
        self.l15.setText("Clear (C)")
        self.l15.setObjectName("l15")
        self.gridLayout_3.addWidget(self.l15, 2, 0, 1, 1)
        self.l16 = QtWidgets.QLabel(self.tab_2)
        self.l16.setText("C")
        self.l16.setObjectName("l16")
        self.gridLayout_3.addWidget(self.l16, 2, 1, 1, 1)
        self.l13 = QtWidgets.QLabel(self.tab_2)
        self.l13.setText("All Clear (AC)")
        self.l13.setObjectName("l13")
        self.gridLayout_3.addWidget(self.l13, 1, 0, 1, 1)
        self.l21 = QtWidgets.QLabel(self.tab_2)
        self.l21.setText("Minus from memory (M-)")
        self.l21.setObjectName("l21")
        self.gridLayout_3.addWidget(self.l21, 6, 0, 1, 1)
        self.l22 = QtWidgets.QLabel(self.tab_2)
        self.l22.setText("Alt + M")
        self.l22.setObjectName("l22")
        self.gridLayout_3.addWidget(self.l22, 6, 1, 1, 1)
        self.l24 = QtWidgets.QLabel(self.tab_2)
        self.l24.setText("M")
        self.l24.setObjectName("l24")
        self.gridLayout_3.addWidget(self.l24, 7, 1, 1, 1)
        self.l25 = QtWidgets.QLabel(self.tab_2)
        self.l25.setText("Get Result")
        self.l25.setObjectName("l25")
        self.gridLayout_3.addWidget(self.l25, 8, 0, 1, 1)
        self.l23 = QtWidgets.QLabel(self.tab_2)
        self.l23.setText("Get memory (M)")
        self.l23.setObjectName("l23")
        self.gridLayout_3.addWidget(self.l23, 7, 0, 1, 1)
        self.l26 = QtWidgets.QLabel(self.tab_2)
        self.l26.setText("Enter or =")
        self.l26.setObjectName("l26")
        self.gridLayout_3.addWidget(self.l26, 8, 1, 1, 1)
        self.l27 = QtWidgets.QLabel(self.tab_2)
        self.l27.setText("Backspace")
        self.l27.setObjectName("l27")
        self.gridLayout_3.addWidget(self.l27, 9, 0, 1, 1)
        self.l28 = QtWidgets.QLabel(self.tab_2)
        self.l28.setText("Backspace")
        self.l28.setObjectName("l28")
        self.gridLayout_3.addWidget(self.l28, 9, 1, 1, 1)
        self.l11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l11.setFont(font)
        self.l11.setText("Action")
        self.l11.setObjectName("l11")
        self.gridLayout_3.addWidget(self.l11, 0, 0, 1, 1)
        self.l12 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l12.setFont(font)
        self.l12.setText("Shortcut")
        self.l12.setObjectName("l12")
        self.gridLayout_3.addWidget(self.l12, 0, 1, 1, 1)
        self.l13_1 = QtWidgets.QLabel(self.tab_2)
        self.l13_1.setText("Clear Error (CE)")
        self.l13_1.setObjectName("l13_1")
        self.gridLayout_3.addWidget(self.l13_1, 3, 0, 1, 1)
        self.l13_2 = QtWidgets.QLabel(self.tab_2)
        self.l13_2.setText("Ctrl + E")
        self.l13_2.setObjectName("l13_2")
        self.gridLayout_3.addWidget(self.l13_2, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "Calculation")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self.l29 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l29.setFont(font)
        self.l29.setText("Action")
        self.l29.setObjectName("l29")
        self.gridLayout1.addWidget(self.l29, 0, 0, 1, 1)
        self.l30 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l30.setFont(font)
        self.l30.setText("Shortcut")
        self.l30.setObjectName("l30")
        self.gridLayout1.addWidget(self.l30, 0, 1, 1, 1)
        self.l32 = QtWidgets.QLabel(self.tab_3)
        self.l32.setText("Alt + 2")
        self.l32.setObjectName("l32")
        self.gridLayout1.addWidget(self.l32, 1, 1, 1, 1)
        self.l33 = QtWidgets.QLabel(self.tab_3)
        self.l33.setText("Make cube root")
        self.l33.setObjectName("l33")
        self.gridLayout1.addWidget(self.l33, 2, 0, 1, 1)
        self.l34 = QtWidgets.QLabel(self.tab_3)
        self.l34.setText("Alt + 3")
        self.l34.setObjectName("l34")
        self.gridLayout1.addWidget(self.l34, 2, 1, 1, 1)
        self.l31 = QtWidgets.QLabel(self.tab_3)
        self.l31.setText("Make root")
        self.l31.setObjectName("l31")
        self.gridLayout1.addWidget(self.l31, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout1, 0, 0, 1, 1)
        self.l35 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l35.setFont(font)
        self.l35.setStyleSheet("background: #e6e6e6; padding-left: 10px;")
        self.l35.setText("For more rooting, use button of advanced panel. \n"
        "Click \'F8\' to open advanced panel.")
        self.l35.setObjectName("l35")
        self.gridLayout_7.addWidget(self.l35, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l36 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l36.setFont(font)
        self.l36.setText("Action")
        self.l36.setObjectName("l36")
        self.gridLayout_2.addWidget(self.l36, 0, 0, 1, 1)
        self.l37 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l37.setFont(font)
        self.l37.setText("Shortcut")
        self.l37.setObjectName("l37")
        self.gridLayout_2.addWidget(self.l37, 0, 1, 1, 1)
        self.l39 = QtWidgets.QLabel(self.tab_3)
        self.l39.setText("Ctrl + number")
        self.l39.setObjectName("l39")
        self.gridLayout_2.addWidget(self.l39, 1, 1, 1, 1)
        self.l38 = QtWidgets.QLabel(self.tab_3)
        self.l38.setText("Put number as power")
        self.l38.setObjectName("l38")
        self.gridLayout_2.addWidget(self.l38, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.l42 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l42.setFont(font)
        self.l42.setStyleSheet("background: #e6e6e6; padding-left: 10px;")
        self.l42.setText("By this way, you can click Ctrl + (1 2, 3, 4, 5, 6, 7, 8,\n"
        "9, 0, .(dot), +, -, *, /) to put them as power. But to \n"
        "put \'(\' and \')\' as power you need to click Ctrl+Alt+9 \n"
        "and Ctrl+Alt+0. ")
        self.l42.setObjectName("l42")
        self.gridLayout_7.addWidget(self.l42, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "Other")
        self.gridLayout_4.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.app_name = QtWidgets.QLabel(ShortcutPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.app_name.setFont(font)
        self.app_name.setText("Calculator")
        self.app_name.setObjectName("app_name")
        self.gridLayout_4.addWidget(self.app_name, 2, 0, 1, 1)
        self.version = QtWidgets.QLabel(ShortcutPage)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.gridLayout_4.addWidget(self.version, 2, 1, 1, 1)
        self.ok_bt = QtWidgets.QPushButton(ShortcutPage)
        self.ok_bt.setText("OK")
        self.ok_bt.setObjectName("ok_bt")
        self.gridLayout_4.addWidget(self.ok_bt, 2, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 8)

        self.ok_bt.clicked.connect(ShortcutPage.close)
        QtCore.QMetaObject.connectSlotsByName(ShortcutPage)
