from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_box_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_box_3.setStyleSheet("QToolButton{background: #e6ffff; font-size:13pt;}")
        self.widget_box_3.setObjectName("widget_box_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_box_3)
        self.gridLayout_3.setContentsMargins(0, 0, 4, 2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bt_37 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_37.sizePolicy().hasHeightForWidth())
        self.bt_37.setSizePolicy(sizePolicy)
        self.bt_37.setStyleSheet("font-family: \"Nw Calc BD\"; font-size: 15pt")
        self.bt_37.setObjectName("bt_37")
        self.gridLayout_3.addWidget(self.bt_37, 2, 3, 1, 1)
        self.bt_32 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_32.sizePolicy().hasHeightForWidth())
        self.bt_32.setSizePolicy(sizePolicy)
        self.bt_32.setObjectName("bt_32")
        self.bt_32.setStyleSheet("font-family: \"Nw Calc BD\"; font-size: 15pt; font-weight: 500;")
        self.gridLayout_3.addWidget(self.bt_32, 0, 1, 1, 1)
        self.bt_35 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_35.sizePolicy().hasHeightForWidth())
        self.bt_35.setSizePolicy(sizePolicy)
        self.bt_35.setObjectName("bt_35")
        self.gridLayout_3.addWidget(self.bt_35, 2, 1, 1, 1)
        self.bt_36 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_36.sizePolicy().hasHeightForWidth())
        self.bt_36.setSizePolicy(sizePolicy)
        self.bt_36.setObjectName("bt_36")
        self.gridLayout_3.addWidget(self.bt_36, 2, 2, 1, 1)
        self.bt_34 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_34.sizePolicy().hasHeightForWidth())
        self.bt_34.setSizePolicy(sizePolicy)
        self.bt_34.setObjectName("bt_34")
        self.gridLayout_3.addWidget(self.bt_34, 0, 3, 1, 1)
        self.bt_33 = QtWidgets.QToolButton(self.widget_box_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_33.sizePolicy().hasHeightForWidth())
        self.bt_33.setSizePolicy(sizePolicy)
        self.bt_33.setObjectName("bt_33")
        self.gridLayout_3.addWidget(self.bt_33, 0, 2, 1, 1)
        self.radio_bt_1 = QtWidgets.QRadioButton(self.widget_box_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_bt_1.setFont(font)
        self.radio_bt_1.setChecked(True)
        self.radio_bt_1.setObjectName("radio_bt_1")
        self.gridLayout_3.addWidget(self.radio_bt_1, 0, 0, 1, 1)
        self.radio_bt_2 = QtWidgets.QRadioButton(self.widget_box_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_bt_2.setFont(font)
        self.radio_bt_2.setObjectName("radio_bt_2")
        self.gridLayout_3.addWidget(self.radio_bt_2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_box_3, 1, 1, 1, 1)
        self.widget_box_1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_box_1.setStyleSheet("QToolButton{background: #ff9999;}")
        self.widget_box_1.setObjectName("widget_box_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.widget_box_1)
        self.gridLayout_1.setContentsMargins(4, 0, 4, 2)
        self.gridLayout_1.setSpacing(2)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.bt_9 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_9.sizePolicy().hasHeightForWidth())
        self.bt_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.bt_9.setFont(font)
        self.bt_9.setStyleSheet("background-color: #80bfff")
        self.bt_9.setObjectName("bt_9")
        self.gridLayout_1.addWidget(self.bt_9, 2, 2, 1, 1)
        self.bt_5 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_5.sizePolicy().hasHeightForWidth())
        self.bt_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_5.setFont(font)
        self.bt_5.setObjectName("bt_5")
        self.gridLayout_1.addWidget(self.bt_5, 0, 4, 1, 1)
        self.bt_1 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_1.sizePolicy().hasHeightForWidth())
        self.bt_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_1.setFont(font)
        self.bt_1.setObjectName("bt_1")
        self.gridLayout_1.addWidget(self.bt_1, 0, 0, 1, 1)
        self.bt_4 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_4.sizePolicy().hasHeightForWidth())
        self.bt_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_4.setFont(font)
        self.bt_4.setObjectName("bt_4")
        self.gridLayout_1.addWidget(self.bt_4, 0, 3, 1, 1)
        self.bt_6 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_6.sizePolicy().hasHeightForWidth())
        self.bt_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_6.setFont(font)
        self.bt_6.setObjectName("bt_6")
        self.gridLayout_1.addWidget(self.bt_6, 0, 5, 1, 1)
        self.bt_3 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_3.sizePolicy().hasHeightForWidth())
        self.bt_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_3.setFont(font)
        self.bt_3.setObjectName("bt_3")
        self.gridLayout_1.addWidget(self.bt_3, 0, 2, 1, 1)
        self.bt_2 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_2.sizePolicy().hasHeightForWidth())
        self.bt_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_2.setFont(font)
        self.bt_2.setObjectName("bt_2")
        self.gridLayout_1.addWidget(self.bt_2, 0, 1, 1, 1)
        self.bt_7 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_7.sizePolicy().hasHeightForWidth())
        self.bt_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_7.setFont(font)
        self.bt_7.setObjectName("bt_7")
        self.gridLayout_1.addWidget(self.bt_7, 2, 0, 1, 1)
        self.bt_8 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_8.sizePolicy().hasHeightForWidth())
        self.bt_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_8.setFont(font)
        self.bt_8.setStyleSheet("background-color: #80bfff")
        self.bt_8.setObjectName("bt_8")
        self.gridLayout_1.addWidget(self.bt_8, 2, 1, 1, 1)
        self.bt_10 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_10.sizePolicy().hasHeightForWidth())
        self.bt_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(15)
        font.setItalic(True)
        self.bt_10.setFont(font)
        self.bt_10.setStyleSheet("background-color: #80bfff")
        self.bt_10.setObjectName("bt_10")
        self.gridLayout_1.addWidget(self.bt_10, 2, 3, 1, 1)
        self.bt_11 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_11.sizePolicy().hasHeightForWidth())
        self.bt_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setItalic(True)
        self.bt_11.setFont(font)
        self.bt_11.setStyleSheet("background-color: #80bfff")
        self.bt_11.setObjectName("bt_11")
        self.gridLayout_1.addWidget(self.bt_11, 2, 4, 1, 1)
        self.bt_12 = QtWidgets.QToolButton(self.widget_box_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_12.sizePolicy().hasHeightForWidth())
        self.bt_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_12.setFont(font)
        self.bt_12.setIconSize(QtCore.QSize(30, 30))
        self.bt_12.setObjectName("bt_12")
        self.gridLayout_1.addWidget(self.bt_12, 2, 5, 1, 1)
        self.gridLayout.addWidget(self.widget_box_1, 1, 0, 1, 1)
        self.widget_box_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_box_2.setStyleSheet("QToolButton{background: #e6ffff; font-size:12pt;}")
        self.widget_box_2.setObjectName("widget_box_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_box_2)
        self.gridLayout_2.setContentsMargins(4, 0, 4, 5)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_15 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_15.sizePolicy().hasHeightForWidth())
        self.bt_15.setSizePolicy(sizePolicy)
        self.bt_15.setObjectName("bt_15")
        self.gridLayout_2.addWidget(self.bt_15, 0, 2, 1, 1)
        self.bt_24 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_24.sizePolicy().hasHeightForWidth())
        self.bt_24.setSizePolicy(sizePolicy)
        self.bt_24.setObjectName("bt_24")
        self.gridLayout_2.addWidget(self.bt_24, 3, 1, 1, 1)
        self.bt_17 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_17.sizePolicy().hasHeightForWidth())
        self.bt_17.setSizePolicy(sizePolicy)
        self.bt_17.setObjectName("bt_17")
        self.gridLayout_2.addWidget(self.bt_17, 0, 4, 1, 1)
        self.bt_14 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_14.sizePolicy().hasHeightForWidth())
        self.bt_14.setSizePolicy(sizePolicy)
        self.bt_14.setObjectName("bt_14")
        self.gridLayout_2.addWidget(self.bt_14, 0, 1, 1, 1)
        self.bt_21 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_21.sizePolicy().hasHeightForWidth())
        self.bt_21.setSizePolicy(sizePolicy)
        self.bt_21.setStyleSheet("QToolButton {background: #ffe066;}")
        self.bt_21.setObjectName("bt_21")
        self.gridLayout_2.addWidget(self.bt_21, 2, 3, 1, 1)
        self.bt_13 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_13.sizePolicy().hasHeightForWidth())
        self.bt_13.setSizePolicy(sizePolicy)
        self.bt_13.setObjectName("bt_13")
        self.gridLayout_2.addWidget(self.bt_13, 0, 0, 1, 1)
        self.bt_16 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_16.sizePolicy().hasHeightForWidth())
        self.bt_16.setSizePolicy(sizePolicy)
        self.bt_16.setObjectName("bt_16")
        self.gridLayout_2.addWidget(self.bt_16, 0, 3, 1, 1)
        self.bt_20 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_20.sizePolicy().hasHeightForWidth())
        self.bt_20.setSizePolicy(sizePolicy)
        self.bt_20.setObjectName("bt_20")
        self.gridLayout_2.addWidget(self.bt_20, 2, 2, 1, 1)
        self.bt_28 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_28.sizePolicy().hasHeightForWidth())
        self.bt_28.setSizePolicy(sizePolicy)
        self.bt_28.setObjectName("bt_28")
        self.gridLayout_2.addWidget(self.bt_28, 4, 0, 1, 1)
        self.bt_29 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_29.sizePolicy().hasHeightForWidth())
        self.bt_29.setSizePolicy(sizePolicy)
        self.bt_29.setObjectName("bt_29")
        self.gridLayout_2.addWidget(self.bt_29, 4, 1, 1, 1)
        self.bt_30 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_30.sizePolicy().hasHeightForWidth())
        self.bt_30.setSizePolicy(sizePolicy)
        self.bt_30.setObjectName("bt_30")
        self.gridLayout_2.addWidget(self.bt_30, 4, 2, 1, 1)
        self.bt_31 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_31.sizePolicy().hasHeightForWidth())
        self.bt_31.setSizePolicy(sizePolicy)
        self.bt_31.setStyleSheet("QToolButton {background: #ffe066;}")
        self.bt_31.setObjectName("bt_31")
        self.gridLayout_2.addWidget(self.bt_31, 4, 3, 1, 1)
        self.bt_27 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_27.sizePolicy().hasHeightForWidth())
        self.bt_27.setSizePolicy(sizePolicy)
        self.bt_27.setStyleSheet("QToolButton {background: #ffe066;}")
        self.bt_27.setObjectName("bt_27")
        self.gridLayout_2.addWidget(self.bt_27, 3, 4, 2, 1)
        self.bt_18 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_18.sizePolicy().hasHeightForWidth())
        self.bt_18.setSizePolicy(sizePolicy)
        self.bt_18.setObjectName("bt_18")
        self.gridLayout_2.addWidget(self.bt_18, 2, 0, 1, 1)
        self.bt_26 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_26.sizePolicy().hasHeightForWidth())
        self.bt_26.setSizePolicy(sizePolicy)
        self.bt_26.setStyleSheet("QToolButton {background: #ffe066;}")
        self.bt_26.setObjectName("bt_26")
        self.gridLayout_2.addWidget(self.bt_26, 3, 3, 1, 1)
        self.bt_23 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_23.sizePolicy().hasHeightForWidth())
        self.bt_23.setSizePolicy(sizePolicy)
        self.bt_23.setObjectName("bt_23")
        self.gridLayout_2.addWidget(self.bt_23, 3, 0, 1, 1)
        self.bt_25 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_25.sizePolicy().hasHeightForWidth())
        self.bt_25.setSizePolicy(sizePolicy)
        self.bt_25.setObjectName("bt_25")
        self.gridLayout_2.addWidget(self.bt_25, 3, 2, 1, 1)
        self.bt_19 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_19.sizePolicy().hasHeightForWidth())
        self.bt_19.setSizePolicy(sizePolicy)
        self.bt_19.setObjectName("bt_19")
        self.gridLayout_2.addWidget(self.bt_19, 2, 1, 1, 1)
        self.bt_22 = QtWidgets.QToolButton(self.widget_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_22.sizePolicy().hasHeightForWidth())
        self.bt_22.setSizePolicy(sizePolicy)
        self.bt_22.setStyleSheet("QToolButton {background: #ffe066;}")
        self.bt_22.setObjectName("bt_22")
        self.gridLayout_2.addWidget(self.bt_22, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.widget_box_2, 2, 0, 1, 1)
        self.widget_box_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_box_4.setStyleSheet("QToolButton{background: #e6ffff; font-size:12pt;}")
        self.widget_box_4.setObjectName("widget_box_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_box_4)
        self.gridLayout_4.setContentsMargins(0, 0, 4, 5)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bt_48 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_48.sizePolicy().hasHeightForWidth())
        self.bt_48.setSizePolicy(sizePolicy)
        self.bt_48.setObjectName("bt_48")
        self.gridLayout_4.addWidget(self.bt_48, 4, 1, 1, 1)
        self.bt_49 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_49.sizePolicy().hasHeightForWidth())
        self.bt_49.setSizePolicy(sizePolicy)
        self.bt_49.setObjectName("bt_49")
        self.gridLayout_4.addWidget(self.bt_49, 4, 2, 1, 1)
        self.bt_39 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_39.sizePolicy().hasHeightForWidth())
        self.bt_39.setSizePolicy(sizePolicy)
        self.bt_39.setObjectName("bt_39")
        self.gridLayout_4.addWidget(self.bt_39, 0, 1, 1, 1)
        self.bt_38 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_38.sizePolicy().hasHeightForWidth())
        self.bt_38.setSizePolicy(sizePolicy)
        self.bt_38.setObjectName("bt_38")
        self.gridLayout_4.addWidget(self.bt_38, 0, 0, 1, 1)
        self.bt_43 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_43.sizePolicy().hasHeightForWidth())
        self.bt_43.setSizePolicy(sizePolicy)
        self.bt_43.setObjectName("bt_43")
        self.gridLayout_4.addWidget(self.bt_43, 2, 2, 1, 1)
        self.bt_47 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_47.sizePolicy().hasHeightForWidth())
        self.bt_47.setSizePolicy(sizePolicy)
        self.bt_47.setObjectName("bt_47")
        self.gridLayout_4.addWidget(self.bt_47, 4, 0, 1, 1)
        self.bt_44 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_44.sizePolicy().hasHeightForWidth())
        self.bt_44.setSizePolicy(sizePolicy)
        self.bt_44.setObjectName("bt_44")
        self.gridLayout_4.addWidget(self.bt_44, 3, 0, 1, 1)
        self.bt_46 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_46.sizePolicy().hasHeightForWidth())
        self.bt_46.setSizePolicy(sizePolicy)
        self.bt_46.setObjectName("bt_46")
        self.gridLayout_4.addWidget(self.bt_46, 3, 2, 1, 1)
        self.bt_41 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_41.sizePolicy().hasHeightForWidth())
        self.bt_41.setSizePolicy(sizePolicy)
        self.bt_41.setObjectName("bt_41")
        self.gridLayout_4.addWidget(self.bt_41, 2, 0, 1, 1)
        self.bt_42 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_42.sizePolicy().hasHeightForWidth())
        self.bt_42.setSizePolicy(sizePolicy)
        self.bt_42.setObjectName("bt_42")
        self.gridLayout_4.addWidget(self.bt_42, 2, 1, 1, 1)
        self.bt_40 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_40.sizePolicy().hasHeightForWidth())
        self.bt_40.setSizePolicy(sizePolicy)
        self.bt_40.setObjectName("bt_40")
        self.gridLayout_4.addWidget(self.bt_40, 0, 2, 1, 1)
        self.bt_45 = QtWidgets.QToolButton(self.widget_box_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_45.sizePolicy().hasHeightForWidth())
        self.bt_45.setSizePolicy(sizePolicy)
        self.bt_45.setObjectName("bt_45")
        self.gridLayout_4.addWidget(self.bt_45, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_box_4, 2, 1, 1, 1)
        self.main_bar = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_bar.sizePolicy().hasHeightForWidth())
        self.main_bar.setSizePolicy(sizePolicy)
        self.main_bar.setStyleSheet("QTextEdit{background: #1ab2ff; border: 4px ridge #737373; border-bottom: 8px ridge gray; padding: 5px; font-size:15pt; font-weight:500; font-family:\"Nw Calc BD\"}")
        self.main_bar.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.main_bar.setObjectName("main_bar")
        self.gridLayout.addWidget(self.main_bar, 0, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        self.menubar.setStyleSheet("QMenuBar{background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 white, stop:.5 rgb(214, 221, 239), stop:1 rgb(225, 230, 246));border-bottom: 2x solid rgb(182,188,204)}")
        self.menubar.setObjectName("menubar")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdvance_Screen = QtWidgets.QAction(MainWindow)
        self.actionAdvance_Screen.setCheckable(True)
        self.actionAdvance_Screen.setText("Advance Screen")
        self.actionAdvance_Screen.setShortcut("F8")
        self.actionAdvance_Screen.setObjectName("actionAdvance_Screen")
        self.actionFullscreen = QtWidgets.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setText("Fullscreen")
        self.actionFullscreen.setShortcut("Ctrl+F")
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setText("Shortcuts")
        self.actionShortcuts.setShortcut("Ctrl+S")
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setText("Exit")
        self.actionExit.setShortcut("Ctrl+Q")
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setText("Copy")
        self.actionCopy.setShortcut("Ctrl+C")
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setText("Cut")
        self.actionCut.setShortcut("Ctrl+X")
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setText("Paste")
        self.actionPaste.setShortcut("Ctrl+V")
        self.actionPaste.setObjectName("actionPaste")
        self.actionNext_History = QtWidgets.QAction(MainWindow)
        self.actionNext_History.setText("Next History")
        self.actionNext_History.setShortcut("Ctrl+Shift+Z")
        self.actionNext_History.setObjectName("actionNext_History")
        self.actionPrevious_History = QtWidgets.QAction(MainWindow)
        self.actionPrevious_History.setText("Previous History")
        self.actionPrevious_History.setShortcut("Ctrl+Z")
        self.actionPrevious_History.setObjectName("actionPrevious_History")
        self.actionClear_History = QtWidgets.QAction(MainWindow)
        self.actionClear_History.setText("Clear History")
        self.actionClear_History.setShortcut("Ctrl+H")
        self.actionClear_History.setObjectName("actionClear_History")
        self.actionAbout_the_Author = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_Author.setText("About Calculator")
        self.actionAbout_the_Author.setObjectName("actionAbout_the_Author")
        self.menuCalculator.addAction(self.actionAdvance_Screen)
        self.menuCalculator.addAction(self.actionFullscreen)
        self.menuCalculator.addAction(self.actionShortcuts)
        self.menuCalculator.addSeparator()
        self.menuCalculator.addAction(self.actionExit)
        self.menuTool.addAction(self.actionCopy)
        self.menuTool.addAction(self.actionCut)
        self.menuTool.addAction(self.actionPaste)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionPrevious_History)
        self.menuTool.addAction(self.actionNext_History)
        self.menuTool.addAction(self.actionClear_History)
        self.menuAbout.addAction(self.actionAbout_the_Author)
        self.menubar.addAction(self.menuCalculator.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.main_bar, self.bt_1)
        MainWindow.setTabOrder(self.bt_1, self.bt_2)
        MainWindow.setTabOrder(self.bt_2, self.bt_3)
        MainWindow.setTabOrder(self.bt_3, self.bt_4)
        MainWindow.setTabOrder(self.bt_4, self.bt_5)
        MainWindow.setTabOrder(self.bt_5, self.bt_6)
        MainWindow.setTabOrder(self.bt_6, self.bt_7)
        MainWindow.setTabOrder(self.bt_7, self.bt_8)
        MainWindow.setTabOrder(self.bt_8, self.bt_9)
        MainWindow.setTabOrder(self.bt_9, self.bt_10)
        MainWindow.setTabOrder(self.bt_10, self.bt_11)
        MainWindow.setTabOrder(self.bt_11, self.bt_12)
        MainWindow.setTabOrder(self.bt_12, self.bt_13)
        MainWindow.setTabOrder(self.bt_13, self.bt_14)
        MainWindow.setTabOrder(self.bt_14, self.bt_15)
        MainWindow.setTabOrder(self.bt_15, self.bt_16)
        MainWindow.setTabOrder(self.bt_16, self.bt_17)
        MainWindow.setTabOrder(self.bt_17, self.bt_18)
        MainWindow.setTabOrder(self.bt_18, self.bt_19)
        MainWindow.setTabOrder(self.bt_19, self.bt_20)
        MainWindow.setTabOrder(self.bt_20, self.bt_21)
        MainWindow.setTabOrder(self.bt_21, self.bt_22)
        MainWindow.setTabOrder(self.bt_22, self.bt_23)
        MainWindow.setTabOrder(self.bt_23, self.bt_24)
        MainWindow.setTabOrder(self.bt_24, self.bt_25)
        MainWindow.setTabOrder(self.bt_25, self.bt_26)
        MainWindow.setTabOrder(self.bt_26, self.bt_27)
        MainWindow.setTabOrder(self.bt_27, self.bt_28)
        MainWindow.setTabOrder(self.bt_28, self.bt_29)
        MainWindow.setTabOrder(self.bt_29, self.bt_30)
        MainWindow.setTabOrder(self.bt_30, self.bt_31)
        MainWindow.setTabOrder(self.bt_31, self.radio_bt_1)
        MainWindow.setTabOrder(self.radio_bt_1, self.bt_32)
        MainWindow.setTabOrder(self.bt_32, self.bt_33)
        MainWindow.setTabOrder(self.bt_33, self.bt_34)
        MainWindow.setTabOrder(self.bt_34, self.radio_bt_2)
        MainWindow.setTabOrder(self.radio_bt_2, self.bt_35)
        MainWindow.setTabOrder(self.bt_35, self.bt_36)
        MainWindow.setTabOrder(self.bt_36, self.bt_37)
        MainWindow.setTabOrder(self.bt_37, self.bt_38)
        MainWindow.setTabOrder(self.bt_38, self.bt_39)
        MainWindow.setTabOrder(self.bt_39, self.bt_40)
        MainWindow.setTabOrder(self.bt_40, self.bt_41)
        MainWindow.setTabOrder(self.bt_41, self.bt_42)
        MainWindow.setTabOrder(self.bt_42, self.bt_43)
        MainWindow.setTabOrder(self.bt_43, self.bt_44)
        MainWindow.setTabOrder(self.bt_44, self.bt_45)
        MainWindow.setTabOrder(self.bt_45, self.bt_46)
        MainWindow.setTabOrder(self.bt_46, self.bt_47)
        MainWindow.setTabOrder(self.bt_47, self.bt_48)
        MainWindow.setTabOrder(self.bt_48, self.bt_49)

        self.main_bar.setText("0")
        self.bt_4.setText("M+")
        self.bt_6.setText("M")
        self.bt_1.setText("AC")
        self.bt_5.setText("M-")
        self.bt_2.setText("CE")
        self.bt_3.setText("MC")
        self.bt_9.setText("\u221B")
        self.bt_7.setText("C")
        self.bt_8.setText("\u221A")
        self.bt_10.setText("x\u00B2")
        self.bt_11.setText("x\u207f")
        self.bt_18.setText("4")
        self.bt_26.setText("\u00d7")
        self.bt_23.setText("7")
        self.bt_25.setText("9")
        self.bt_19.setText("5")
        self.bt_22.setText("+")
        self.bt_15.setText("3")
        self.bt_24.setText("8")
        self.bt_17.setText(")")
        self.bt_14.setText("2")
        self.bt_21.setText("-")
        self.bt_13.setText("1")
        self.bt_16.setText("(")
        self.bt_20.setText("6")
        self.bt_28.setText("\u00B1")
        self.bt_29.setText("0")
        self.bt_30.setText(".")
        self.bt_31.setText("\u00f7")
        self.bt_27.setText("=")
        self.bt_48.setText("rad")
        self.bt_49.setText("×10\u02e3")
        self.bt_39.setText("cos")
        self.bt_38.setText("sin")
        self.bt_43.setText("tan⁻¹")
        self.bt_47.setText("deg")
        self.bt_44.setText("log")
        self.bt_46.setText("ln")
        self.bt_41.setText("sin⁻¹")
        self.bt_42.setText("cos⁻¹")
        self.bt_40.setText("tan")
        self.bt_45.setText("Log \u2093 x")
        self.bt_37.setText("\u0177")
        self.bt_32.setText("\u03c0")
        self.bt_35.setText("!")
        self.bt_36.setText(",")
        self.bt_34.setText("^")
        self.bt_33.setText("e")
        self.radio_bt_1.setText("Degree")
        self.radio_bt_2.setText("Radian")
        self.menuCalculator.setTitle("Calculator")
        self.menuTool.setTitle("Tool")
        self.menuAbout.setTitle("About")
