from PyQt5 import QtCore, QtGui, QtWidgets


class UiShortcutPage(object):
    def setup_ui(self, shortcut_page):
        shortcut_page.setObjectName("shortcut_page")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        shortcut_page.setFont(font)
        shortcut_page.setStyleSheet("")
        self.label = QtWidgets.QLabel(shortcut_page)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background: #d1d1d1;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(shortcut_page)
        self.tabWidget.setGeometry(QtCore.QRect(11, 60, 321, 341))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 9, 301, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l11_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_5.setObjectName("l11_5")
        self.gridLayout.addWidget(self.l11_5, 6, 0, 1, 1)
        self.l11_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_3.setObjectName("l11_3")
        self.gridLayout.addWidget(self.l11_3, 7, 0, 1, 1)
        self.l1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 0, 0, 1, 1)
        self.l2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 0, 1, 1, 1)
        self.l11_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_1.setObjectName("l11_1")
        self.gridLayout.addWidget(self.l11_1, 5, 0, 1, 1)
        self.l8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l8.setObjectName("l8")
        self.gridLayout.addWidget(self.l8, 3, 1, 1, 1)
        self.l7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l7.setObjectName("l7")
        self.gridLayout.addWidget(self.l7, 3, 0, 1, 1)
        self.l4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l4.setObjectName("l4")
        self.gridLayout.addWidget(self.l4, 1, 1, 1, 1)
        self.l5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l5.setObjectName("l5")
        self.gridLayout.addWidget(self.l5, 2, 0, 1, 1)
        self.l6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l6.setObjectName("l6")
        self.gridLayout.addWidget(self.l6, 2, 1, 1, 1)
        self.l3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l3.setObjectName("l3")
        self.gridLayout.addWidget(self.l3, 1, 0, 1, 1)
        self.l9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l9.setObjectName("l9")
        self.gridLayout.addWidget(self.l9, 4, 0, 1, 1)
        self.l10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l10.setObjectName("l10")
        self.gridLayout.addWidget(self.l10, 4, 1, 1, 1)
        self.l11_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_4.setObjectName("l11_4")
        self.gridLayout.addWidget(self.l11_4, 7, 1, 1, 1)
        self.l11_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_2.setObjectName("l11_2")
        self.gridLayout.addWidget(self.l11_2, 5, 1, 1, 1)
        self.l11_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l11_6.setObjectName("l11_6")
        self.gridLayout.addWidget(self.l11_6, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 301, 291))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l17.setObjectName("l17")
        self.gridLayout_3.addWidget(self.l17, 4, 0, 1, 1)
        self.l20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l20.setObjectName("l20")
        self.gridLayout_3.addWidget(self.l20, 5, 1, 1, 1)
        self.l18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l18.setObjectName("l18")
        self.gridLayout_3.addWidget(self.l18, 4, 1, 1, 1)
        self.l19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l19.setObjectName("l19")
        self.gridLayout_3.addWidget(self.l19, 5, 0, 1, 1)
        self.l14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l14.setObjectName("l14")
        self.gridLayout_3.addWidget(self.l14, 1, 1, 1, 1)
        self.l15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l15.setObjectName("l15")
        self.gridLayout_3.addWidget(self.l15, 2, 0, 1, 1)
        self.l16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l16.setObjectName("l16")
        self.gridLayout_3.addWidget(self.l16, 2, 1, 1, 1)
        self.l13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l13.setObjectName("l13")
        self.gridLayout_3.addWidget(self.l13, 1, 0, 1, 1)
        self.l21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l21.setObjectName("l21")
        self.gridLayout_3.addWidget(self.l21, 6, 0, 1, 1)
        self.l22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l22.setObjectName("l22")
        self.gridLayout_3.addWidget(self.l22, 6, 1, 1, 1)
        self.l24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l24.setObjectName("l24")
        self.gridLayout_3.addWidget(self.l24, 7, 1, 1, 1)
        self.l25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l25.setObjectName("l25")
        self.gridLayout_3.addWidget(self.l25, 8, 0, 1, 1)
        self.l23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l23.setObjectName("l23")
        self.gridLayout_3.addWidget(self.l23, 7, 0, 1, 1)
        self.l26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l26.setObjectName("l26")
        self.gridLayout_3.addWidget(self.l26, 8, 1, 1, 1)
        self.l27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l27.setObjectName("l27")
        self.gridLayout_3.addWidget(self.l27, 9, 0, 1, 1)
        self.l28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l28.setObjectName("l28")
        self.gridLayout_3.addWidget(self.l28, 9, 1, 1, 1)
        self.l11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l11.setFont(font)
        self.l11.setObjectName("l11")
        self.gridLayout_3.addWidget(self.l11, 0, 0, 1, 1)
        self.l12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l12.setFont(font)
        self.l12.setObjectName("l12")
        self.gridLayout_3.addWidget(self.l12, 0, 1, 1, 1)
        self.l13_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l13_1.setObjectName("l13_1")
        self.gridLayout_3.addWidget(self.l13_1, 3, 0, 1, 1)
        self.l13_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.l13_2.setObjectName("l13_2")
        self.gridLayout_3.addWidget(self.l13_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayoutWidget1 = QtWidgets.QWidget(self.tab1)
        self.gridLayoutWidget1.setGeometry(QtCore.QRect(10, 10, 301, 81))
        self.gridLayoutWidget1.setObjectName("gridLayoutWidget1")
        self.gridLayout1 = QtWidgets.QGridLayout(self.gridLayoutWidget1)
        self.gridLayout1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout1.setObjectName("gridLayout1")
        self.l29 = QtWidgets.QLabel(self.gridLayoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l29.setFont(font)
        self.l29.setObjectName("l29")
        self.gridLayout1.addWidget(self.l29, 0, 0, 1, 1)
        self.l30 = QtWidgets.QLabel(self.gridLayoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l30.setFont(font)
        self.l30.setObjectName("l30")
        self.gridLayout1.addWidget(self.l30, 0, 1, 1, 1)
        self.l32 = QtWidgets.QLabel(self.gridLayoutWidget1)
        self.l32.setObjectName("l32")
        self.gridLayout1.addWidget(self.l32, 1, 1, 1, 1)
        self.l33 = QtWidgets.QLabel(self.gridLayoutWidget1)
        self.l33.setObjectName("l33")
        self.gridLayout1.addWidget(self.l33, 2, 0, 1, 1)
        self.l34 = QtWidgets.QLabel(self.gridLayoutWidget1)
        self.l34.setObjectName("l34")
        self.gridLayout1.addWidget(self.l34, 2, 1, 1, 1)
        self.l31 = QtWidgets.QLabel(self.gridLayoutWidget1)
        self.l31.setObjectName("l31")
        self.gridLayout1.addWidget(self.l31, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 301, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l36.setFont(font)
        self.l36.setObjectName("l36")
        self.gridLayout_2.addWidget(self.l36, 0, 0, 1, 1)
        self.l37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l37.setFont(font)
        self.l37.setObjectName("l37")
        self.gridLayout_2.addWidget(self.l37, 0, 1, 1, 1)
        self.l39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.l39.setObjectName("l39")
        self.gridLayout_2.addWidget(self.l39, 1, 1, 1, 1)
        self.l40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.l40.setObjectName("l40")
        self.gridLayout_2.addWidget(self.l40, 2, 0, 1, 1)
        self.l41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.l41.setObjectName("l41")
        self.gridLayout_2.addWidget(self.l41, 2, 1, 1, 1)
        self.l38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.l38.setObjectName("l38")
        self.gridLayout_2.addWidget(self.l38, 1, 0, 1, 1)
        self.l35 = QtWidgets.QLabel(self.tab1)
        self.l35.setGeometry(QtCore.QRect(0, 100, 321, 51))
        self.l35.setStyleSheet("background: #e6e6e6; padding-left: 10px;")
        self.l35.setObjectName("l35")
        self.l42 = QtWidgets.QLabel(self.tab1)
        self.l42.setGeometry(QtCore.QRect(0, 250, 321, 51))
        self.l42.setStyleSheet("background: #e6e6e6; padding-left: 10px;")
        self.l42.setObjectName("l42")
        self.tabWidget.addTab(self.tab1, "")
        self.ok_bt = QtWidgets.QPushButton(shortcut_page)
        self.ok_bt.setGeometry(QtCore.QRect(250, 409, 75, 25))
        self.ok_bt.setObjectName("ok_bt")
        self.app_name = QtWidgets.QLabel(shortcut_page)
        self.app_name.setGeometry(QtCore.QRect(10, 411, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.app_name.setFont(font)
        self.app_name.setObjectName("app_name")
        self.version = QtWidgets.QLabel(shortcut_page)
        self.version.setGeometry(QtCore.QRect(86, 412, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.version.setFont(font)
        self.version.setObjectName("version")

        self.retranslateUi(shortcut_page)
        self.tabWidget.setCurrentIndex(0)
        self.ok_bt.clicked.connect(shortcut_page.close)
        QtCore.QMetaObject.connectSlotsByName(shortcut_page)

    def retranslateUi(self, shortcut_page):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("shortcut_page", "Shortcuts"))
        self.l11_5.setText(_translate("shortcut_page", "Zoom out on the screen"))
        self.l11_3.setText(_translate("shortcut_page", "Exit"))
        self.l1.setText(_translate("shortcut_page", "Action"))
        self.l2.setText(_translate("shortcut_page", "Shortcut"))
        self.l11_1.setText(_translate("shortcut_page", "Zoom in on the screen"))
        self.l8.setText(_translate("shortcut_page", "Ctrl + F"))
        self.l7.setText(_translate("shortcut_page", "Fullscreen mode toggle"))
        self.l4.setText(_translate("shortcut_page", "Ctrl + C"))
        self.l5.setText(_translate("shortcut_page", "Paste"))
        self.l6.setText(_translate("shortcut_page", "Ctrl + V"))
        self.l3.setText(_translate("shortcut_page", "Copy"))
        self.l9.setText(_translate("shortcut_page", "Show Shortcuts"))
        self.l10.setText(_translate("shortcut_page", "Ctrl + S"))
        self.l11_4.setText(_translate("shortcut_page", "Ctrl + Q"))
        self.l11_2.setText(_translate("shortcut_page", "Ctrl + Mouse Wheel Up"))
        self.l11_6.setText(_translate("shortcut_page", "Ctrl + Mouse Wheel Down"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("shortcut_page", "General"))
        self.l17.setText(_translate("shortcut_page", "Memory Clear (MC)"))
        self.l20.setText(_translate("shortcut_page", "Shift + M"))
        self.l18.setText(_translate("shortcut_page", "Ctrl + M"))
        self.l19.setText(_translate("shortcut_page", "Add to memory (M+)"))
        self.l14.setText(_translate("shortcut_page", "Alt + C"))
        self.l15.setText(_translate("shortcut_page", "Clear (C)"))
        self.l16.setText(_translate("shortcut_page", "C"))
        self.l13.setText(_translate("shortcut_page", "All Clear (AC)"))
        self.l21.setText(_translate("shortcut_page", "Minus from memory (M-)"))
        self.l22.setText(_translate("shortcut_page", "Alt + M"))
        self.l24.setText(_translate("shortcut_page", "M"))
        self.l25.setText(_translate("shortcut_page", "Get Result (=)"))
        self.l23.setText(_translate("shortcut_page", "Get memory (M)"))
        self.l26.setText(_translate("shortcut_page", "Enter or ="))
        self.l27.setText(_translate("shortcut_page", "Backspace (<--)"))
        self.l28.setText(_translate("shortcut_page", "Backspace"))
        self.l11.setText(_translate("shortcut_page", "Action"))
        self.l12.setText(_translate("shortcut_page", "Shortcut"))
        self.l13_1.setText(_translate("shortcut_page", "Clear Error (CE)"))
        self.l13_2.setText(_translate("shortcut_page", "E"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("shortcut_page", "Calculation"))
        self.l29.setText(_translate("shortcut_page", "Action"))
        self.l30.setText(_translate("shortcut_page", "Shortcut"))
        self.l32.setText(_translate("shortcut_page", "Alt + 2"))
        self.l33.setText(_translate("shortcut_page", "Make cube root"))
        self.l34.setText(_translate("shortcut_page", "Alt + 3"))
        self.l31.setText(_translate("shortcut_page", "Make root"))
        self.l36.setText(_translate("shortcut_page", "Action"))
        self.l37.setText(_translate("shortcut_page", "Shortcut"))
        self.l39.setText(_translate("shortcut_page", "Ctrl + 2"))
        self.l40.setText(_translate("shortcut_page", "Make cube"))
        self.l41.setText(_translate("shortcut_page", "Ctrl + 3"))
        self.l38.setText(_translate("shortcut_page", "Make square"))
        self.l35.setText(_translate("shortcut_page", "By this way you can also click - Alt + 4, Alt + 5, \n"
                                                     "Alt + 6, Alt + 7, Alt + 8, Alt + 9"))
        self.l42.setText(_translate("shortcut_page", "By this way you can also click - Ctrl + 4, Ctrl + 5, \n"
                                                     "Ctrl + 6, Ctrl + 7, Ctrl + 8, Ctrl + 9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("shortcut_page", "Other"))
        self.ok_bt.setText(_translate("shortcut_page", "Ok"))
        self.app_name.setText(_translate("shortcut_page", "Calculator"))
        self.version.setText(_translate("shortcut_page", "v1.2.2"))

